### ISSUE TITLE
Fix error: argument of type 'NoneType' is not iterable 

### ISSUE THREAD

**Issue by tanaha2002** [chanheehi/Video-Speech-Recognition-and-Subtitle-Generation#1]
I got the error below if i run `app.py`:
libc = ctypes.CDLL(libc_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

And method to fix it is you need to re-install the right package from openai `pip uninstall whisper`
then `pip install git+https://github.com/openai/whisper.git`

**Comment by chanheehi** [comment]
Thank you for your interest.

We have taken your feedback into account,

and we have modified the 7th line in the requirements.txt for dependency resolution from "whisper" to "openai-whisper"
